language: go # 声明构建语言环境
sudo: false # 开启基于容器的Travis CI任务，让编译效率更高。

notifications: # 每次构建的时候是否通知，如果不想收到通知，那就设置false吧(email: false,也可以是Slack)
  email:
    recipients:
  on_success: change
  on_failure: always

go:
  - 1.14.4

install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls

script: # 集成脚本
  - overalls -project=$GOPATH/src/github.com/go-xman/bdd_demo -covermode=count -ignore='mock,.git,_vendor'
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go test ./... -coverpkg=./...

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
