// Code generated by MockGen. DO NOT EDIT.
// Source: order_repository.go

// Package repositories is a generated GoMock package.
package repositories

import (
	gomock "github.com/golang/mock/gomock"
	models "order/models"
	reflect "reflect"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// FindAllOrdersByUserID mocks base method.
func (m *MockOrderRepository) FindAllOrdersByUserID(userID int) (models.Orders, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllOrdersByUserID", userID)
	ret0, _ := ret[0].(models.Orders)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllOrdersByUserID indicates an expected call of FindAllOrdersByUserID.
func (mr *MockOrderRepositoryMockRecorder) FindAllOrdersByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllOrdersByUserID", reflect.TypeOf((*MockOrderRepository)(nil).FindAllOrdersByUserID), userID)
}
